name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.21'

      - name: Install dependancies
        run: bun install

      - name: Build binaries
        run: npm run build-binaries

      - name: Create tar.gz files
        run: |
          mkdir -p binaries/compressed
          tar -czvf binaries/compressed/chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz -C binaries/linux cli-linux-x64
          tar -czvf binaries/compressed/chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz -C binaries/linux cli-linux-arm64
          tar -czvf binaries/compressed/chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz -C binaries/macos cli-macos-arm64
          tar -czvf binaries/compressed/chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz -C binaries/macos cli-macos-x64
          tar -czvf binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz -C binaries/windows cli-windows-x64.exe

      - name: Generate checksums
        run: |
          shasum -a 256 binaries/compressed/chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz > binaries/compressed/chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz.sha256
          shasum -a 256 binaries/compressed/chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz > binaries/compressed/chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz.sha256
          shasum -a 256 binaries/compressed/chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz > binaries/compressed/chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz.sha256
          shasum -a 256 binaries/compressed/chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz > binaries/compressed/chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz.sha256
          shasum -a 256 binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz > binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz.sha256

      - name: Generate combined checksums file
        run: |
          cat binaries/compressed/*.sha256 > binaries/compressed/chasm-cli-${{ github.ref_name }}-checksums.txt

      - name: Create symlinks for latest tarballs
        run: |
          ln -sf chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz binaries/compressed/chasm-cli-linux-x64-latest.tar.gz
          ln -sf chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz binaries/compressed/chasm-cli-linux-arm64-latest.tar.gz
          ln -sf chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz binaries/compressed/chasm-cli-darwin-arm64-latest.tar.gz
          ln -sf chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz binaries/compressed/chasm-cli-darwin-x64-latest.tar.gz
          ln -sf chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz binaries/compressed/chasm-cli-windows-x64-latest.tar.gz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz
          asset_name: chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_name: chasm-cli-linux-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz
          asset_name: chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz.sha256
          asset_name: chasm-cli-linux-arm64-${{ github.ref_name }}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz
          asset_name: chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz.sha256
          asset_name: chasm-cli-darwin-arm64-${{ github.ref_name }}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz
          asset_name: chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_name: chasm-cli-darwin-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz
          asset_name: chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_name: chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Combined Checksums File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/compressed/chasm-cli-${{ github.ref_name }}-checksums.txt
          asset_name: chasm-cli-${{ github.ref_name }}-checksums.txt
          asset_content_type: text/plain

      - name: Update version and checksum in nuspec
        run: |
          VERSION=${{ github.ref_name }}
          CHECKSUM=$(cat binaries/compressed/chasm-cli-windows-x64-${{ github.ref_name }}.tar.gz.sha256 | awk '{print $1}')
          sed -i "s/<version>.*<\/version>/<version>$VERSION<\/version>/" choco-package/chasm-cli.nuspec
          sed -i "s/sha256=\".*\"/sha256=\"$CHECKSUM\"/" choco-package/chasm-cli.nuspec

      - name: Generate and publish Chocolatey package
        run: |
          choco pack choco-package/chasm-cli.nuspec
          choco push choco-package/chasm-cli.*.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
